ERROR:zadanie_1.py:Error devide to zero
